In [30]:
import pandas as pd

In [31]:
df = pd.read_csv("messy_zomato_dataset.csv",encoding='utf-8')

In [32]:
df

,name,rate,votes,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Onesta,3.4/5,-5.0,YES,No,"1,200",Other
1,KFC,NaN,708.0,YES,YES,NaN,Other
2,Dominos,NaN,-5.0,NaN,No,NaN,buffet
3,San Churro,NaN,92.0,No,Yes,NaN,dining
4,Onesta,4.6/5,-5.0,no,NaN,"1,200",Cafes
...,...,...,...,...,...,...,...
145,Cafe Coffee Day,NEW,NaN,Yes,NaN,"1,200",Buffet
146,Cafe Coffee Day,NaN,-5.0,No,NaN,NaN,Dining
147,KFC,2.8/5,556.0,NaN,YES,NaN,dining
148,Burger King,NEW,NaN,Yes,Yes,NaN,Buffet
149,Cafe Coffee Day,3.9/5,-5.0,No,no,-300,Other

In [33]:
df.isna().sum()

name                            0
rate                           34
votes                          56
online_order                   23
book_table                     36
approx_cost(for two people)    45
listed_in(type)                 0
dtype: int64

In [34]:
df.describe()

            votes
count   94.000000
mean   287.010638
std    351.306394
min     -5.000000
25%     -5.000000
50%     -5.000000
75%    649.000000
max    983.000000

## Level 1 ##

In [35]:
# 1.What columns have mixed data types? Why is that dangerous?
# df.info()
# df['name'].unique() # has no mix data types only strings.
# df['rate'].unique() # rate has mix datatypes as it has nan,-,2.0/5 (str,special characters and fraction but is also a string)
# df['votes'].unique() #votes is pretty good nan is there which indicates the missing value other than it is float64
df['online_order'].unique() #it is a string with nan as missing value in it
df['book_table'].unique()  #it is string with nan as missing value and thses two online_orer and book_table are categorical and are incosistent
df['approx_cost(for two people)'].unique() #it is mix damm sure has 1,200 nan 
df['listed_in(type)'].unique() #no only string but incosistent take a look at other and Other and also cafes and Cafes

# it is dangerous because we cant perform the desired operation in this dataset and even if we performed we will get faulty result that wont be any benficial for us and also the operation we perofed in this data wil yield unexpected and diffeernt output
#in zist 
    # incosistent data will produce umepected and incosistent output

<StringArray>
['Other', 'buffet', 'dining', 'Cafes', 'Buffet', 'cafes', 'Dining', 'other']
Length: 8, dtype: str

In [36]:
# #2. Which columns contain missing values? Are they random or patterned?
# df.info()
# here we can clearly see except name and listed_in(type) every other colums contain missing values(NaN).
df.head(20)
# i cant say they are randomed or patterned yet can use need to test the corelation between columns and many other test to chcek wheter they are randomed or patterned

,name,rate,votes,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Onesta,3.4/5,-5.0,YES,No,"1,200",Other
1,KFC,NaN,708.0,YES,YES,NaN,Other
2,Dominos,NaN,-5.0,NaN,No,NaN,buffet
3,San Churro,NaN,92.0,No,Yes,NaN,dining
4,Onesta,4.6/5,-5.0,no,NaN,"1,200",Cafes
5,Dominos,-,NaN,No,no,-300,Buffet
6,San Churro,-,-5.0,YES,no,-300,Buffet
7,KFC,-,-5.0,Yes,no,-300,Buffet
8,Dominos,2.0/5,983.0,no,No,"1,200",cafes
9,Cafe Nova,NaN,NaN,No,no,NaN,buffet
10,San Churro,-,825.0,Yes,no,-300,Cafes
11,Starbucks,-,NaN,No,NaN,"1,200",Other
12,KFC,2.1/5,-5.0,no,NaN,"1,200",cafes
13,McDonald's,4.0/5,887.0,YES,YES,"1,200",Other
14,Cafe Coffee Day,NaN,-5.0,No,no,"1,200",Other
15,Starbucks,3.6 /5,346.0,Yes,YES,1997,Other
16,San Churro,NaN,NaN,no,YES,NaN,dining
17,San Churro,2.8/5,827.0,no,no,1514,Other
18,Pizza Hut,1.5/5,862.0,No,Yes,NaN,Dining
19,Pizza Hut,NaN,-5.0,NaN,NaN,NaN,cafes

In [37]:
#3.identify all invalid values in rate
    # What do NEW, -, None actually mean?
    # What will you convert them into?
df['rate']
df['rate'].unique()
# Basically It '-' can be cell left to be filled later and not filled.
df.loc[df['rate'] == 'NEW']
#after using the above function i can be sure that NEW refering to the new rate that is to be provided to the customer but is not fixed and same for none
#if we just conclude these 'NEW' '-' and "none" they are  the incositent values in the cell that will hinder the analysis operation

# i will convert them into NaN or use aggreate values to fill if they are super necesary or if we have plenty of data like 1000 rows + i will simply drop that row(but this will be my harsh and last step)

,name,rate,votes,online_order,book_table,approx_cost(for two people),listed_in(type)
20,Cafe Coffee Day,NEW,-5.0,no,no,1510,cafes
28,KFC,NEW,700.0,Yes,YES,-300,Cafes
29,Burger King,NEW,NaN,No,No,NaN,other
37,Pizza Hut,NEW,NaN,NaN,no,-300,dining
38,KFC,NEW,700.0,No,no,NaN,Dining
44,Pizza Hut,NEW,-5.0,Yes,no,"1,200",Other
51,McDonald's,NEW,-5.0,YES,No,NaN,Other
53,McDonald's,NEW,-5.0,No,NaN,-300,buffet
58,San Churro,NEW,180.0,no,YES,1643,cafes
59,Burger King,NEW,307.0,Yes,No,-300,dining
61,Cafe Coffee Day,NEW,-5.0,no,Yes,NaN,Other
75,Cafe Nova,NEW,NaN,Yes,NaN,1357,Buffet
76,McDonald's,NEW,674.0,NaN,NaN,816,Cafes
77,San Churro,NEW,511.0,YES,no,1480,buffet
82,San Churro,NEW,-5.0,No,no,"1,200",dining
92,Cafe Coffee Day,NEW,660.0,YES,NaN,"1,200",Dining
97,KFC,NEW,NaN,NaN,Yes,NaN,cafes
101,San Churro,NEW,NaN,no,no,NaN,dining
104,Starbucks,NEW,-5.0,NaN,NaN,-300,Dining
106,Dominos,NEW,NaN,No,YES,-300,Dining
116,Starbucks,NEW,-5.0,NaN,NaN,-300,Cafes
119,McDonald's,NEW,-5.0,YES,Yes,1841,Cafes
122,Cafe Nova,NEW,-5.0,Yes,No,NaN,Other
124,Dominos,NEW,-5.0,Yes,NaN,-300,cafes
132,Pizza Hut,NEW,-5.0,No,NaN,795,Cafes
139,Pizza Hut,NEW,536.0,NaN,Yes,"1,200",buffet
143,Burger King,NEW,-5.0,no,no,"1,200",Buffet
145,Cafe Coffee Day,NEW,NaN,Yes,NaN,"1,200",Buffet
148,Burger King,NEW,NaN,Yes,Yes,NaN,Buffet

In [38]:
#3. Clean approx_cost
    # Why is "1,200" a problem?
    # What happens if you don’t fix it?
df['approx_cost(for two people)'] = df['approx_cost(for two people)'].astype(str).str.replace(',', '').replace('nan', pd.NA)
df['approx_cost(for two people)'] = pd.to_numeric(df['approx_cost(for two people)'], errors='coerce')
# 1,200 is a string so is a problem for compution as it is in consitent data.
# if we dont fix that we wont be able to perform the numeric computation.

In [39]:
df['approx_cost(for two people)'].describe()

count     105.000000
mean      721.914286
std       776.948210
min      -300.000000
25%      -300.000000
50%      1200.000000
75%      1200.000000
max      1997.000000
Name: approx_cost(for two people), dtype: float64

In [40]:
#4. Standardize online_order and book_table
    # How many unique values are there actually?
df['online_order'].unique()
#to standaradize online_order fist of all/
#     1.remove the value other than yes no 
#     2.convert yes no in a standard form 
#     3.convert the yes and no into boolean expression like true/false or 0/1
# same goes for book_table
df['book_table'].unique()

<StringArray>
['No', 'YES', 'Yes', nan, 'no']
Length: 5, dtype: str

## LEVEL 2

In [ ]:
# Are restaurant names reliable as a unique identifier?
    # If not, what’s your strategy?
# u basically trying to say using name as primary key.
# no resturanent name is not yet reilable as unique identifier in this case because of Case Sensitivity issue
# insted we can correct them and create a new colum and  unique id like RST101 like thinsg that will make it more unique and reliable

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         150 non-null    str
 1   rate                         116 non-null    str
 2   votes                        94 non-null     float64
 3   online_order                 127 non-null    str
 4   book_table                   114 non-null    str
 5   approx_cost(for two people)  105 non-null    float64
 6   listed_in(type)              150 non-null    str
dtypes: float64(2), str(5)
memory usage: 8.3 KB

In [45]:
df.head(10)

,name,rate,votes,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Onesta,3.4/5,-5.0,YES,No,1200.0,Other
1,KFC,NaN,708.0,YES,YES,NaN,Other
2,Dominos,NaN,-5.0,NaN,No,NaN,buffet
3,San Churro,NaN,92.0,No,Yes,NaN,dining
4,Onesta,4.6/5,-5.0,no,NaN,1200.0,Cafes
5,Dominos,-,NaN,No,no,-300.0,Buffet
6,San Churro,-,-5.0,YES,no,-300.0,Buffet
7,KFC,-,-5.0,Yes,no,-300.0,Buffet
8,Dominos,2.0/5,983.0,no,No,1200.0,cafes
9,Cafe Nova,NaN,NaN,No,no,NaN,buffet

In [ ]:
# # You have duplicates:
#     # Same name, different ratings, different votes
#     # 👉 What will you do?
#     # drop?
#     # average?
#     # keep latest?
#     # WHY?
# i will keep average beacuse the data could be taken at different date and i respect that and droping it will be a bad choice beacuse haveing multiple data for same thing is pretty good.
# keeping latest is also a good option but we should also repesct the past data as it is of that resturant.

In [ ]:
# # votes contains negative values
#     # What does that tell you about data quality?
#     # Fix or remove?
# df['votes'].describe()
# # count     94.000000
# # mean     287.010638
# # std      351.306394
# # min       -5.000000
# # 25%       -5.000000
# # 50%       -5.000000
# # 75%      649.000000
# # max      983.000000
# # Name: votes, dtype: float64
# i did df.shape and got (150,7) just look clearly there are alot of misssing values . the quality of data is poor and mean is 287 and min is -5 what the heck is that i will eliminate that value and use aggregate in their but it is not a good idea as we got the mean from those vlaues right so first remove that and keep empty space and take a look how many of them where negative if they were many them it is a problem i will tell to wait for another month 
# but if they are few aggregate and fill

count     94.000000
mean     287.010638
std      351.306394
min       -5.000000
25%       -5.000000
50%       -5.000000
75%      649.000000
max      983.000000
Name: votes, dtype: float64

In [52]:
df.shape

(150, 7)

In [ ]:
# # Category column (listed_in(type))
#     # How many actual categories exist vs fake ones created by bad formatting?
# df['listed_in(type)'].unique()
# here other buffet dining cafes only exist that is 4 categories rest of them are either Case Sensitivity issue or repeated

<StringArray>
['Other', 'buffet', 'dining', 'Cafes', 'Buffet', 'cafes', 'Dining', 'other']
Length: 8, dtype: str

In [58]:
df[df['rate'].duplicated(keep=False)].head(50)

,name,rate,votes,online_order,book_table,approx_cost(for two people),listed_in(type)
0,Onesta,3.4/5,-5.0,YES,No,1200.0,Other
1,KFC,NaN,708.0,YES,YES,NaN,Other
2,Dominos,NaN,-5.0,NaN,No,NaN,buffet
3,San Churro,NaN,92.0,No,Yes,NaN,dining
5,Dominos,-,NaN,No,no,-300.0,Buffet
6,San Churro,-,-5.0,YES,no,-300.0,Buffet
7,KFC,-,-5.0,Yes,no,-300.0,Buffet
8,Dominos,2.0/5,983.0,no,No,1200.0,cafes
9,Cafe Nova,NaN,NaN,No,no,NaN,buffet
10,San Churro,-,825.0,Yes,no,-300.0,Cafes
11,Starbucks,-,NaN,No,NaN,1200.0,Other
12,KFC,2.1/5,-5.0,no,NaN,1200.0,cafes
14,Cafe Coffee Day,NaN,-5.0,No,no,1200.0,Other
16,San Churro,NaN,NaN,no,YES,NaN,dining
17,San Churro,2.8/5,827.0,no,no,1514.0,Other
19,Pizza Hut,NaN,-5.0,NaN,NaN,NaN,cafes
20,Cafe Coffee Day,NEW,-5.0,no,no,1510.0,cafes
23,Cafe Coffee Day,-,746.0,Yes,No,1200.0,other
24,McDonald's,2.0/5,-5.0,No,YES,1200.0,Dining
26,KFC,4.1/5,590.0,no,no,1668.0,Dining
27,Cafe Nova,NaN,NaN,No,Yes,1991.0,cafes
28,KFC,NEW,700.0,Yes,YES,-300.0,Cafes
29,Burger King,NEW,NaN,No,No,NaN,other
32,Burger King,NaN,NaN,NaN,Yes,906.0,buffet
33,San Churro,4.7 /5,146.0,YES,NaN,-300.0,buffet
34,Starbucks,-,-5.0,no,no,897.0,Dining
36,Dominos,NaN,NaN,No,YES,-300.0,Cafes
37,Pizza Hut,NEW,NaN,NaN,no,-300.0,dining
38,KFC,NEW,700.0,No,no,NaN,Dining
39,Onesta,-,NaN,YES,no,1228.0,dining
40,Dominos,1.9/5,676.0,no,no,NaN,buffet
41,Dominos,-,NaN,No,no,-300.0,Other
43,Cafe Nova,-,NaN,No,Yes,1200.0,buffet
44,Pizza Hut,NEW,-5.0,Yes,no,1200.0,Other
45,KFC,4.1/5,-5.0,NaN,YES,-300.0,Cafes
46,McDonald's,-,NaN,Yes,Yes,1200.0,Other
47,KFC,-,-5.0,NaN,YES,-300.0,Other
48,Dominos,4.2 /5,NaN,NaN,No,NaN,Cafes
49,Dominos,NaN,-5.0,no,no,-300.0,other
50,McDonald's,NaN,NaN,Yes,YES,1839.0,cafes
51,McDonald's,NEW,-5.0,YES,No,NaN,Other
53,McDonald's,NEW,-5.0,No,NaN,-300.0,buffet
56,Cafe Coffee Day,2.0 /5,285.0,YES,no,-300.0,buffet
57,Pizza Hut,-,415.0,YES,NaN,-300.0,Dining
58,San Churro,NEW,180.0,no,YES,1643.0,cafes
59,Burger King,NEW,307.0,Yes,No,-300.0,dining
60,KFC,NaN,NaN,no,NaN,NaN,dining
61,Cafe Coffee Day,NEW,-5.0,no,Yes,NaN,Other
62,Burger King,NaN,529.0,NaN,NaN,NaN,buffet
63,Starbucks,1.8 /5,968.0,YES,YES,580.0,cafes

In [59]:
df[df['name'] == 'KFC']

,name,rate,votes,online_order,book_table,approx_cost(for two people),listed_in(type)
1,KFC,NaN,708.0,YES,YES,NaN,Other
7,KFC,-,-5.0,Yes,no,-300.0,Buffet
12,KFC,2.1/5,-5.0,no,NaN,1200.0,cafes
21,KFC,1.0/5,NaN,NaN,YES,NaN,Buffet
26,KFC,4.1/5,590.0,no,no,1668.0,Dining
28,KFC,NEW,700.0,Yes,YES,-300.0,Cafes
38,KFC,NEW,700.0,No,no,NaN,Dining
45,KFC,4.1/5,-5.0,NaN,YES,-300.0,Cafes
47,KFC,-,-5.0,NaN,YES,-300.0,Other
60,KFC,NaN,NaN,no,NaN,NaN,dining
64,KFC,4.1/5,662.0,no,NaN,986.0,buffet
69,KFC,3.3/5,-5.0,NaN,NaN,NaN,Buffet
93,KFC,-,962.0,YES,Yes,1751.0,other
97,KFC,NEW,NaN,NaN,Yes,NaN,cafes
98,KFC,1.4/5,NaN,YES,YES,1851.0,Other
110,KFC,-,NaN,NaN,Yes,1200.0,Cafes
147,KFC,2.8/5,556.0,NaN,YES,NaN,dining

## level 3

In [61]:
df.describe()

            votes  approx_cost(for two people)
count   94.000000                   105.000000
mean   287.010638                   721.914286
std    351.306394                   776.948210
min     -5.000000                  -300.000000
25%     -5.000000                  -300.000000
50%     -5.000000                  1200.000000
75%    649.000000                  1200.000000
max    983.000000                  1997.000000

In [62]:
df['rate']=df['rate'].str.strip().str.replace(' ','',regex=False).str.split('/').str[0]

In [71]:
df['rate']=df['rate'].replace('-','nan',regex=False).replace('NEW','nan',regex=False)

In [73]:
df['rate']=df['rate'].astype(float)

In [74]:
df.describe()

            rate       votes  approx_cost(for two people)
count  63.000000   94.000000                   105.000000
mean    3.152381  287.010638                   721.914286
std     1.063751  351.306394                   776.948210
min     1.000000   -5.000000                  -300.000000
25%     2.100000   -5.000000                  -300.000000
50%     3.300000   -5.000000                  1200.000000
75%     4.050000  649.000000                  1200.000000
max     5.000000  983.000000                  1997.000000

In [82]:
# Find logical inconsistencies
    # High rating + very low votes → trust or not?
    # Low cost + luxury category → possible?
df[(df['rate'] > 4) & (df['votes'] < df['votes'].mean())]
# 	name	rate	votes	online_order	book_table	approx_cost(for two people)	listed_in(type)
# 4	Onesta	4.6	-5.0	no	NaN	1200.0	Cafes
# 33	San Churro	4.7	146.0	YES	NaN	-300.0	buffet
# 45	KFC	4.1	-5.0	NaN	YES	-300.0	Cafes
# 52	Onesta	4.3	-5.0	no	no	1200.0	Dining
# 89	Starbucks	4.8	-5.0	no	no	-300.0	dining
# 118	Onesta	4.2	218.0	YES	No	1303.0	cafes
# 129	Burger King	4.8	-5.0	No	YES	1200.0	Dining
# 140	Dominos	4.1	-5.0	No	no	NaN	cafes
# first of all is raates and votes related 
#low cost and luxury is possible if the customer got the discount but since there is no discount colum so we nned to think twicely

,name,rate,votes,online_order,book_table,approx_cost(for two people),listed_in(type)
4,Onesta,4.6,-5.0,no,NaN,1200.0,Cafes
33,San Churro,4.7,146.0,YES,NaN,-300.0,buffet
45,KFC,4.1,-5.0,NaN,YES,-300.0,Cafes
52,Onesta,4.3,-5.0,no,no,1200.0,Dining
89,Starbucks,4.8,-5.0,no,no,-300.0,dining
118,Onesta,4.2,218.0,YES,No,1303.0,cafes
129,Burger King,4.8,-5.0,No,YES,1200.0,Dining
140,Dominos,4.1,-5.0,No,no,NaN,cafes

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         150 non-null    str
 1   rate                         63 non-null     float64
 2   votes                        94 non-null     float64
 3   online_order                 127 non-null    str
 4   book_table                   114 non-null    str
 5   approx_cost(for two people)  105 non-null    float64
 6   listed_in(type)              150 non-null    str
dtypes: float64(3), str(4)
memory usage: 8.3 KB

In [ ]:
# Outlier detection:
    # Which column has extreme values?
    # How do you define “extreme”?
df.describe()
# first thing first extrem values comes only to numeric column her in rate there is no extreme and in votes there is extreme and in approx_cost(for two people) there is extrem.
# extreme is the value that doesnt fit the value trend like here if we take value of mean in votes its 287 and max is 649 and q1 q2 q3 also doesnt show supporting trend for max value 

# rate	votes	approx_cost(for two people)
# count	63.000000	94.000000	105.000000
# mean	3.152381	287.010638	721.914286
# std	1.063751	351.306394	776.948210
# min	1.000000	-5.000000	-300.000000
# 25%	2.100000	-5.000000	-300.000000
# 50%	3.300000	-5.000000	1200.000000
# 75%	4.050000	649.000000	1200.000000
# max	5.000000	983.000000	1997.000000

            rate       votes  approx_cost(for two people)
count  63.000000   94.000000                   105.000000
mean    3.152381  287.010638                   721.914286
std     1.063751  351.306394                   776.948210
min     1.000000   -5.000000                  -300.000000
25%     2.100000   -5.000000                  -300.000000
50%     3.300000   -5.000000                  1200.000000
75%     4.050000  649.000000                  1200.000000
max     5.000000  983.000000                  1997.000000

In [85]:
Q3 = df['votes'].quantile(0.75)
Q1 = df['votes'].quantile(0.25)
IQR = Q3 - Q1

outliers = df[(df['votes'] < Q1 - 1.5*IQR) | (df['votes'] > Q3 + 1.5*IQR)]

In [88]:
print(outliers)

Empty DataFrame
Columns: [name, rate, votes, online_order, book_table, approx_cost(for two people), listed_in(type)]
Index: []

In [ ]:
# # Should you normalize:
#     # votes?
#     # cost?
#     # 👉 WHY or WHY NOT?
# i shouldnt beacuse normalization is topic of mL . and i am not cosidering that yet